name: Generate PDF

on:
  push:
    branches:
    - master

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: html to pdf
      uses: misaelnieto/web_to_pdf_action@master
      with:
        webPageURL: https://edm00se.codes/cv/
        outputFile: ./auto-EM-CV.pdf
        usePuppeteer: true
        pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - uses: stefanzweifel/git-auto-commit-action@v5
